# package.yaml
name: mcp-auth-server-base
version: 1.1.0
description: Use with MCP server projects that depend on @prmichaelsen/mcp-auth.
author: Patrick Michaelsen
license: MIT
homepage: https://github.com/prmichaelsen/mcp-auth-server-base
repository: https://github.com/prmichaelsen/acp-mcp-auth-server-base.git

# Release configuration
release:
  branch: main

# Package contents
# Add files here as you create them
# Use @acp.pattern-create, @acp.command-create, @acp.design-create
# These commands automatically update this section
contents:
  patterns:
    - name: mcp-auth-server-base.server-wrapping.md
    - name: mcp-auth-server-base.auth-provider-jwt.md
    - name: mcp-auth-server-base.auth-provider-oauth.md
    - name: mcp-auth-server-base.auth-provider-apikey.md
    - name: mcp-auth-server-base.auth-provider-env.md
    - name: mcp-auth-server-base.token-resolver.md
    - name: mcp-auth-server-base.static-server.md
    - name: mcp-auth-server-base.error-handling.md
    - name: mcp-auth-server-base.logging.md
    - name: mcp-auth-server-base.health-check.md
    - name: mcp-auth-server-base.cors-configuration.md
    - name: mcp-auth-server-base.environment-configuration.md
    - name: mcp-auth-server-base.docker-multistage.md
    - name: mcp-auth-server-base.cloud-build.md
    - name: mcp-auth-server-base.cloud-run-deployment.md
    - name: mcp-auth-server-base.secrets-management.md
    - name: mcp-auth-server-base.jest-configuration.md
    - name: mcp-auth-server-base.testing-auth-providers.md
  
  commands:
    - name: mcp-auth-server-base.init.md
    - name: mcp-auth-server-base.validate.md
    - name: mcp-auth-server-base.deploy.md
    - name: mcp-auth-server-base.setup-secrets.md
    - name: mcp-auth-server-base.logs.md
    - name: mcp-auth-server-base.generate-dockerfile.md
    - name: mcp-auth-server-base.generate-cloudbuild.md
    - name: mcp-auth-server-base.add-auth-provider.md
    - name: mcp-auth-server-base.mcp-auth-version-check.md
    - name: mcp-auth-server-base.mcp-auth-version-update.md
  
  scripts:
    - name: mcp-auth-server-base.validate.sh
  
  designs:
    - name: mcp-auth-server-base.architecture.md
    - name: mcp-auth-server-base.security-considerations.md
  
  templates:
    - name: config/tsconfig.json
    - name: config/jest.config.js
    - name: config/.dockerignore
    - name: config/.env.example
    - name: config/.gitignore
    - name: docker/Dockerfile.development
    - name: docker/Dockerfile.production
    - name: deployment/cloudbuild.yaml
    - name: src/index.ts.template
    - name: src/auth/platform-jwt-provider.ts.template
    - name: src/auth/platform-token-resolver.ts.template
    - name: scripts/upload-secrets.ts
    - name: scripts/test-auth.ts
    - name: package/package.json.template

# Compatibility
requires:
  acp: >=2.8.0

# Tags for discovery
tags:
  - mcp
  - auth
  - server
  - starter
