# package.yaml
name: mcp-auth-server-base
version: 1.0.0
description: Use with MCP server projects that depend on @prmichaelsen/mcp-auth.
author: Patrick Michaelsen
license: MIT
homepage: https://github.com/prmichaelsen/mcp-auth-server-base
repository: https://github.com/prmichaelsen/acp-mcp-auth-server-base.git

# Release configuration
release:
  branch: main

# Package contents
# Add files here as you create them
# Use @acp.pattern-create, @acp.command-create, @acp.design-create
# These commands automatically update this section
contents:
  patterns:
    - name: mcp-auth-server-base.server-wrapping.md
    - name: mcp-auth-server-base.auth-provider-jwt.md
    - name: mcp-auth-server-base.auth-provider-oauth.md
    - name: mcp-auth-server-base.auth-provider-apikey.md
    - name: mcp-auth-server-base.auth-provider-env.md
    - name: mcp-auth-server-base.token-resolver.md
    - name: mcp-auth-server-base.static-server.md
    - name: mcp-auth-server-base.error-handling.md
    - name: mcp-auth-server-base.logging.md
    - name: mcp-auth-server-base.health-check.md
    - name: mcp-auth-server-base.cors-configuration.md
    - name: mcp-auth-server-base.environment-configuration.md
    - name: mcp-auth-server-base.docker-multistage.md
    - name: mcp-auth-server-base.cloud-build.md
    - name: mcp-auth-server-base.cloud-run-deployment.md
    - name: mcp-auth-server-base.secrets-management.md
    - name: mcp-auth-server-base.jest-configuration.md
    - name: mcp-auth-server-base.testing-auth-providers.md
  
  commands: []
  
  designs:
    - name: mcp-auth-server-base.architecture.md

# Compatibility
requires:
  acp: >=2.8.0

# Tags for discovery
tags:
  - mcp
  - auth
  - server
  - starter
